proxy:
  build: .
  command: rackup
  ports:
    - '8081:8081'
  volumes:
    - '$DOCKER_CERT_PATH:/home/.docker'
  environment:
    - DOCKER_CERT_PATH=/home/.docker
    - DOCKER_HOST
    - DOCKER_TLS_VERIFY
