api:
  build: .
  command: node index.js
  user: root
  ports:
    - '4000:4000'
  links:
    - 'db'
    - 'dbtest'
  volumes:
    - '$DOCKER_CERT_PATH:/home/.docker'
    - '.:/arkis-api'
  environment:
    - DOCKER_CERT_PATH=/home/.docker
    - DOCKER_HOST
    - DOCKER_TLS_VERIFY
    - JWT_SECRET_KEY
    - GITHUB_CLIENT_ID
    - GITHUB_SECRET_KEY
    - DIGITAL_OCEAN_TOKEN
    - CODECLIMATE_REPO_TOKEN

db:
  image: postgres:9.4.2
  expose:
    - '5432'
  volumes:
    - '/dockerproxy-db:/var/lib/postgresql/data'

dbtest:
  extends:
    file: docker-compose.yml
    service: db
  volumes:
    - '/arkis-dbtest:/var/lib/postgresql/data'

# TODO: use new docker-compose extend to
# extend each client config from service test
# and just replace build path.
#test:
  #build: test/clients/dockerode
  #links:
    #- api
  #environment:
    #- DOCKER_HOST=http://api
    #- DOCKER_PORT=4000
  #tty: true

#cli:
  #build: test/clients/docker-cli
  #links:
    #- api
  #environment:
    #- DOCKER_HOST=tcp://api:4000
  #privileged: true
  #tty: true
